name: Scheduled release job

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run:
    name: Update latest release
    runs-on: ubuntu-latest
    steps:
    - name: Install packages
      run: "sudo apt update && sudo apt install -y node-semver jq"
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Get current version
      id: version
      run: echo "::set-output name=version::$(head -n 1 version)"
    - name: Get pypi latest version
      id: newver
      run: echo "::set-output name=newver::$(curl 'https://pypi.org/pypi/feeluown/json' | jq -r '.info.version')"
    - name: Compare version
      id: compare
      run: |
        ver=$(semver ${{ steps.version.outputs.version }} ${{ steps.newver.outputs.newver }})
        if [ "$ver" != "${{ steps.version.outputs.version }}" ];
        then
          echo "::set-output name=update::1"
        fi
    - name: Update version
      run: |
        echo -n "${{ steps.newver.outputs.newver }}" > ./version
    - name: Update tag
      if: ${{ steps.compare.outputs.update == 1 }}
      uses: EndBug/add-and-commit@v4
      with:
        author_name: FeelUOwn release job
        author_email: release@feeluown.org
        message: "Update to version ${{ steps.newver.outputs.newver }}"
        add: "version"
        tag: "v${{ steps.newver.outputs.newver }}"
      env:
        GITHUB_TOKEN: ${{ secrets.DISTRIBUTION_TOKEN }}
